---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Los privilegios mínimos requeridos de ONTAP varían en función de los plugins de SnapCenter que utilice para la protección de datos. 
---
= Se requieren privilegios de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los privilegios mínimos requeridos de ONTAP varían en función de los plugins de SnapCenter que utilice para la protección de datos.



== Privilegios mínimos requeridos de ONTAP

Todos los plugins de SnapCenter requieren los siguientes privilegios mínimos.

|===
| Comandos de acceso total: Privilegios mínimos requeridos para ONTAP 8.3 y versiones posteriores 


| event generate-autosupport-log 


| se muestra el historial del trabajo
detención de trabajo 


| lun
lun create
eliminación de lun
igroup de lun añadido
crear lun igroup
lun igroup eliminado
cambio de nombre de lun igroup
lun igroup show
asignación de lun de nodos adicionales
se crea la asignación de lun
se elimina la asignación de lun
asignación de lun quitar nodos de generación de informes
se muestra el mapa de lun
modificación de lun
movimiento de lun en volumen
lun desconectada
lun conectada
reserva persistente de lun clara
cambio de tamaño de lun
serie de lun
muestra de lun 


| destinos de listas de snapmirror
regla adicional de la política de snapmirror
regla de modificación de la política de snapmirror
regla de eliminación de la política de snapmirror
la política de snapmirror
restauración de snapmirror
de snapmirror
historial de snapmirror
actualización de snapmirror
conjunto de actualizaciones de snapmirror 


| Versión 


| crear el clon de volumen
show de clon de volumen
inicio de división de clon de volumen
detención de división de clon de volumen
cree el volumen
destrucción del volumen
crear el archivo de volumen
uso show-disk del archivo de volumen
volumen sin conexión
volumen en línea
modificación del volumen
crear el qtree de volúmenes
eliminación de qtree de volumen
modificación del qtree del volumen
se muestra volume qtree
restricción de volumen
visualización de volumen
crear snapshots de volumen
eliminación de snapshots de volumen
modificación de las copias de snapshot de volumen
cambio de nombre de copias de snapshot de volumen
restauración de copias snapshot de volumen
archivo de restauración de snapshots de volumen
visualización de copias de snapshot de volumen
desmonte el volumen 


| vserver cifs
vserver cifs share create
eliminación de vserver cifs share
se muestra vserver shadowcopy
visualización de vserver cifs share
visualización de vserver cifs
política de exportación de vserver
creación de política de exportación de vserver
eliminación de la política de exportación de vserver
creación de reglas de política de exportación de vserver
aparece la regla de política de exportación de vserver
visualización de la política de exportación de vserver
vserver iscsi
se muestra la conexión iscsi del vserver
se muestra vserver
interfaz de red
grupos de recuperación tras fallos de interfaces de red
se muestra la interfaz de red 
|===
|===
| Comandos de solo lectura: Privilegios mínimos requeridos para ONTAP 8.3 y versiones posteriores 


| vserver
nivel vserver 
|===

NOTE: Puede ignorar los mensajes de advertencia sobre los comandos Vserver no compatibles.



== Información adicional sobre ONTAP

* Si utiliza ONTAP 8.2.x:
+
Debe iniciar sesión como `vsadmin` En la máquina virtual de almacenamiento con los privilegios adecuados para las operaciones del plugin de SnapCenter para VMware vSphere.

* Si utiliza ONTAP 8.3 y versiones posteriores:
+
Debe iniciar sesión como `vsadmin` o con un rol que tenga los privilegios mínimos indicados en las tablas anteriores.

* Debe ser el administrador del clúster para crear y gestionar los roles de usuario. Puede asociar los usuarios con la máquina virtual de almacenamiento del clúster o con la máquina virtual de almacenamiento.

