---
sidebar: sidebar 
permalink: scpivs44_minimum_vcenter_privileges_required.html 
keywords:  
summary: Antes de iniciar la implementación del plugin de SnapCenter para VMware vSphere, debe asegurarse de contar con los privilegios mínimos de vCenter requeridos. 
---
= Privilegios mínimos requeridos de vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de iniciar la implementación del plugin de SnapCenter para VMware vSphere, debe asegurarse de contar con los privilegios mínimos de vCenter requeridos.



== Privilegios requeridos para la función de administrador de vCenter

Datastore.AllocateSpace
Datastore.Browse
Almacén de datos.Eliminar
Datastore.FileManagement
Datastore.Move
Datastore.Renombrar
Extensión.Registro
Extensión.Anular registro
Extensión.Actualizar
Host.Config.AdvancedConfig
Host.Config.Resources
Host.Config.Settings
Host.Config.Storage
Host.Local.CreateVM
Host.Local.DeleteVM
Host.Local.ReconfigVM
Red.Asignar
Resource.ApplyRecommendation
Resource.AssignVMToPool
Resource.ColdMigrate
Resource.HotMigrate
Resource.QueryVMotion
System.Anonymous
Lectura del sistema
Vista del sistema
Tarea.Crear
Tarea.Actualizar
VirtualMachine.Config.AddExistingDisk
VirtualMachine.Config.AddNewDisk
VirtualMachine.Config.AdvancedConfig
VirtualMachine.Config.ReloadFromPath
VirtualMachine.Config.RemoveDisk
VirtualMachine.Config.Resource
VirtualMachine.GuestOperations.Execute
VirtualMachine.GuestOperations.Modify
VirtualMachine.GuestOperations.Query
VirtualMachine.Interact.PowerOff
VirtualMachine.Interact.PowerOn
VirtualMachine.Inventory.Create
VirtualMachine.Inventory.CreateFromExisting
VirtualMachine.Inventory.Delete
VirtualMachine.Inventory.Move
VirtualMachine.Inventory.Register
VirtualMachine.Inventory.Anular registro
VirtualMachine.State.CreateSnapshot
VirtualMachine.State.RemoveSnapshot
VirtualMachine.State.RevertToSnapshot



== Privilegios requeridos específicos del plugin de SnapCenter para VMware vCenter

|===


| *Privilegios* | *Etiqueta* 


| NetappSCV.Guest.RestoreFile | Restauración de archivos invitados 


| NetappSCV.Recovery.MountUnMount | Montar/desmontar 


| NetappSCV.Backup.DeleteBackupJob | Eliminar grupo de recursos/copia de seguridad 


| NetappSCV.Configure.ConfigureStorageSystems.Delete | Quitar sistemas de almacenamiento 


| NetappSCV.View | Ver 


| NetappSCV.Recovery.RecoverVM | Recuperar la máquina virtual 


| NetappSCV.Configure.ConfigureStorageSystems.AddUpdate | Añadir/modificar sistemas de almacenamiento 


| NetappSCV.Backup.BackupNow | Realice su backup ahora 


| NetappSCV.Guest.Configure | Configuración de invitado 


| NetappSCV.Configure.ConfigureSnapCenter Server | Configure el servidor SnapCenter 


| NetappSCV.Backup.BackupExeted | Crear grupo de recursos 
|===